- name: check k8s
  hosts: all
  vars:
    - ansible_ssh_host_key_checking: False 
  gather_facts: false


  tasks:
    - name: check git
      ansible.builtin.shell: which git
      register: result
      until: result.rc==0
      retries: 20
      delay: 20
    - name: git clone kubespray
      ansible.builtin.git:
        repo: https://github.com/kubernetes-sigs/kubespray.git
        dest: ./kubespray
        version: release-2.21
    - name: check pip
      ansible.builtin.shell: which pip
      register: result
      until: result.rc ==0
      retries: 10
      delay: 20
    - name: install requirements
      ansible.builtin.pip:
        requirements: requirements.txt
        chdir: /home/pugachevvv/kubespray
      become: yes
    - name: copy hosts file to remote
      ansible.builtin.copy:
        src: inventory.yml
        dest: ./kubespray/inventory/sample/hosts.yml
    - name: copy rsa file
      ansible.builtin.copy:
        src: ./ssh/id_rsa
        dest: .ssh/id_rsa
        owner: pugachevvv
        group: pugachevvv
        mode: '0600'
      become: yes